# tools/github_tools.py

from github import Github
import os

def search_issues(max_results=5):
    """
    Search GitHub for open Python bug issues in small projects.
    """
    g = Github(os.getenv("GITHUB_TOKEN"))

    query = "language:python label:bug state:open stars:10..100"

    print("\n🔍 Searching GitHub for Python bug issues in small projects...\n")

    issues = g.search_issues(query=query, sort="created", order="desc")

    found = []
    count = 0
    for issue in issues:
        if count >= max_results:
            break
        found.append({
            "number": issue.number,
            "title": issue.title,
            "body": issue.body or "No description provided.",
            "repo": issue.repository.full_name,
            "url": issue.html_url,
            "issue_obj": issue  # keep reference for later commenting
        })
        count += 1

    return found


def display_issues(issues):
    """
    Print a numbered list of issues for the user to pick from.
    """
    print("📋 Found the following issues:\n")
    for i, issue in enumerate(issues):
        print(f"  [{i+1}] {issue['repo']} #{issue['number']}")
        print(f"       {issue['title']}")
        print(f"       {issue['url']}\n")


def pick_issue(issues):
    """
    Ask the user to pick an issue by number.
    """
    while True:
        try:
            choice = int(input("👉 Enter the number of the issue you want to solve: "))
            if 1 <= choice <= len(issues):
                return issues[choice - 1]
            else:
                print(f"Please enter a number between 1 and {len(issues)}")
        except ValueError:
            print("Please enter a valid number")


def post_comment(issue_obj, pr_description):
    """
    Post the generated PR description as a comment on the GitHub issue.
    """
    comment = f"""
## 🤖 Multi-Agent System Analysis

This issue was automatically analyzed by a multi-agent pipeline.
Here is the proposed fix and PR description:

---

{pr_description}

---
*Generated by a LangGraph Multi-Agent System*
"""
    issue_obj.create_comment(comment)
    print(f"\n✅ Comment posted on GitHub issue!")
